name: "Multi-arch Docker Image"

on:
  workflow_dispatch:

jobs:
  docker:
    name: Building and Pushing Multi-arch Docker Image
    runs-on: ubuntu-latest
    env:
      WEBWORK2_GIT_URL: https://github.com/openwebwork/webwork2.git
      WEBWORK2_BRANCH: main
      PG_GIT_URL: https://github.com/openwebwork/pg.git
      PG_BRANCH: main
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-clipboard:latest
